### PR TITLE
Specify 'all' as stream type to expect against both stdout and stderr

### PR DESCRIPTION
**Pull request by brandon-fryslie**

### CODE REVIEW

**Comment by indexzero** [comment]
lgtm. thoughts @sam-github? Would be a minor version bump since it is new functionality.

**Comment by sam-github** [comment]
Seems reasonable. Lacks unit tests, but has docs. I'd rather expectations could be explicitly against stderr or stdout, treating them as the same seems weird, but that's a bigger change I've no time for.

**Comment by indexzero** [comment]
Alright. Merge at will.

**Comment by sam-github** [comment]
> Would be a minor version bump since it is new functionality.

@indexzero nexpect is still in 0.x, so semver doesn't apply. Should publish as 1.0.0, agreed?

**Comment by indexzero** [comment]
:+1: sounds good.

**Pull request merged**
